project:
  type: website
  output-dir: docs

website:
  title: "TarynDowden.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Research.qmd
      - Experience.qmd
      - Community.qmd

format:
  html:
    theme: solar
    css: styles.css
    toc: true

editor: visual

